services:
  - type: web
    name: flask-oc
    env: python
    rootDir: flask-oc
    buildCommand: pip install -r requirements.txt
    # Forza el cwd al subdirectorio para que run.py encuentre 'app'
    startCommand: cd flask-oc && gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        value: c5d9c204a5b266373959ef08b3afed57
      - key: DATABASE_URL
        sync: false
