services:
  - type: web
    name: flask-oc
    env: python
    rootDir: flask-oc          # subcarpeta donde est√° run.py y requirements.txt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        value: c5d9c204a5b266373959ef08b3afed57
      - key: postgresql://mitienda_1dfk_user:vOoOxMy16OtkWpZjWVgEwi0T43ZDR3zZ@dpg-d4mgebje5dus738ahcfg-a.oregon-postgres.render.com/mitienda_1dfk
        sync: false            # ponla en el dashboard para no exponerla
    plan: free
    autoDeploy: true
    runtime: python
    pythonVersion: 3.11