services:
  - type: web
    name: flask-oc
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn 'app.main:create_app()'
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
